'use client';

import { useEffect, useMemo, useState } from 'react';
import { runRippleAnalysis, proposalForFinding, proposedRequirement } from '@/lib/ripple/scenario';
import { registerRippleTools } from '@/lib/webmcp';
import type { Entity, Finding, SourceSystem, WorkItem } from '@/lib/ripple/types';

type View = 'overview' | 'change' | 'impact' | 'execution' | 'evidence';
type Decision = 'pending' | 'approved' | 'rejected';

const nav: { id: View; label: string; number: string }[] = [
  { id: 'overview', label: 'Workspace', number: '01' },
  { id: 'change', label: 'Policy change', number: '02' },
  { id: 'impact', label: 'Impact review', number: '03' },
  { id: 'execution', label: 'Execution', number: '04' },
  { id: 'evidence', label: 'Evidence map', number: '05' },
];

const sourceLabels: Record<SourceSystem, string> = {
  confluence:'Confluence', google_sheets:'Google Sheets', jira:'Jira', azure_boards:'Azure Boards', sharepoint:'SharePoint', github_actions:'GitHub Actions', azure_pipelines:'Azure Pipelines', entra_id:'Microsoft Entra ID', okta:'Okta', aws:'AWS', azure:'Azure', terraform_cloud:'Terraform Cloud', splunk:'Splunk', datadog:'Datadog', servicenow:'ServiceNow', vanta:'Vanta', throughline:'RippleTrace',
};

const sourceGroups = [
  { label:'Policy', sources:['confluence'] as SourceSystem[], note:'Wexler Security Standard v4.2' },
  { label:'Controls', sources:['google_sheets'] as SourceSystem[], note:'SOC 2 and ISO control matrix' },
  { label:'Delivery', sources:['jira','azure_boards'] as SourceSystem[], note:'Two engineering organizations' },
  { label:'Decisions', sources:['sharepoint'] as SourceSystem[], note:'Architecture decision records' },
  { label:'Verification', sources:['github_actions','azure_pipelines'] as SourceSystem[], note:'Automated tests and attestations' },
  { label:'Identity', sources:['entra_id','okta'] as SourceSystem[], note:'Corporate and acquired business unit' },
  { label:'Infrastructure', sources:['aws','azure','terraform_cloud'] as SourceSystem[], note:'Commercial and Gov workloads' },
  { label:'Operations', sources:['splunk','datadog','servicenow','vanta'] as SourceSystem[], note:'Logs, exceptions, continuous monitoring' },
];

type ConnectedRecord = { id:string; system:SourceSystem; kind:string; title:string; ref:string; status:string; owner:string };
const connectedRecords:ConnectedRecord[] = [
  {id:'policy',system:'confluence',kind:'Policy page',title:'Wexler Security Standard · Privileged access',ref:'WSEC / pages / 884215',status:'Approved · v4.2',owner:'Security Governance'},
  {id:'matrix',system:'google_sheets',kind:'Control matrix',title:'SOC 2 / ISO 27001 control mapping',ref:'SOC2-matrix!B114',status:'1 control affected',owner:'GRC'},
  {id:'jira',system:'jira',kind:'Work item',title:'FIDO2 security key rollout',ref:'PLAT-4488',status:'In progress',owner:'Platform Identity'},
  {id:'boards',system:'azure_boards',kind:'Work item',title:'Enforce Conditional Access on release pipelines',ref:'12844',status:'In progress',owner:'Developer Experience'},
  {id:'decision',system:'sharepoint',kind:'Architecture decision',title:'Break-glass credentials remain outside the IdP',ref:'ADR / 2026-02-breakglass',status:'Accepted',owner:'Cloud SRE'},
  {id:'gha',system:'github_actions',kind:'Automated test',title:'Conditional Access requires MFA',ref:'identity / actions / runs / 4471',status:'Passing · now insufficient',owner:'Platform Identity'},
  {id:'pipeline',system:'azure_pipelines',kind:'Pipeline test',title:'Service-principal credential age',ref:'wexler-gov / drift-check / 913',status:'Passing',owner:'Gov Cloud'},
  {id:'entra',system:'entra_id',kind:'Identity policy',title:'CA-0031 · Privileged MFA policy',ref:'Conditional Access / CA-0031',status:'Enabled · weak fallback',owner:'Identity Platform'},
  {id:'okta',system:'okta',kind:'Identity evidence',title:'Contractor group membership export',ref:'grp_contractor_prod',status:'196 days old',owner:'Acquired Business Unit'},
  {id:'terraform',system:'terraform_cloud',kind:'Infrastructure run',title:'wexler-identity-prod',ref:'run-8Kq2mT',status:'Applied',owner:'Cloud Platform'},
  {id:'exception',system:'servicenow',kind:'Exception approval',title:'Contractor SRE authentication exception',ref:'RITM0084412',status:'Requires reapproval',owner:'Risk Acceptance'},
  {id:'monitor',system:'vanta',kind:'Continuous monitor',title:'MFA enforcement across privileged accounts',ref:'Monitor / identity-mfa-04',status:'Needs attention',owner:'Security Assurance'},
];

export default function ClauseFlowWorkspace() {
  const analysis = useMemo(runRippleAnalysis, []);
  const proposals = useMemo(() => analysis.impact.findings.map(proposalForFinding), [analysis]);
  const [view, setView] = useState<View>('overview');
  const [analyzed, setAnalyzed] = useState(true);
  const [decisions, setDecisions] = useState<Record<string, Decision>>({});
  const [activity, setActivity] = useState<string[]>(['AC-2 impact review opened by Dana Lindqvist.','Vanta monitor identity-mfa-04 reported four resources requiring attention.','Azure Pipeline drift-check #913 completed successfully.']);
  const [toast, setToast] = useState('');

  const decided = Object.values(decisions).filter((x) => x !== 'pending').length;
  const approved = Object.values(decisions).filter((x) => x === 'approved').length;
  const readiness = analyzed ? Math.min(analysis.baseline.score, analysis.revised.score + approved) : analysis.baseline.score;

  const notify = (message:string) => { setToast(message); window.setTimeout(() => setToast(''), 2400); };
  const runAnalysis = () => { setAnalyzed(true); setView('impact'); setActivity((a) => [`AC-2 impact review refreshed · ${analysis.impact.findings.length} findings.`, ...a]); notify('Impact review refreshed.'); };
  const decide = (id:string, decision:Decision) => { setDecisions((d) => ({...d,[id]:decision})); const p=proposals.find((x)=>x.id===id); setActivity((a)=>[`${decision === 'approved' ? 'Approved' : 'Rejected'} ${id}: ${p?.title}`, ...a]); notify(`${id} ${decision} by Dana Lindqvist.`); };

  useEffect(() => {
    registerRippleTools({
      getGraph: () => analysis.snapshot,
      analyzeImpact: () => { runAnalysis(); return analysis.impact; },
      calculateReadiness: () => analyzed ? analysis.revised : analysis.baseline,
      createReview: () => { runAnalysis(); return proposals; },
      explainFinding: (id) => analysis.impact.findings.find((f)=>f.id===id) ?? {error:'Finding not found'},
      approveProposal: (id) => { decide(id,'approved'); return {id,status:'approved',reviewedBy:'d.lindqvist@wexler.example'}; },
      rejectProposal: (id) => { decide(id,'rejected'); return {id,status:'rejected',reviewedBy:'d.lindqvist@wexler.example'}; },
    });
  }, [analysis, analyzed, proposals]);

  return <main className="rt-app">
    <header className="rt-topbar"><div className="rt-brand"><div className="rt-mark">R</div><div><strong>RippleTrace</strong><span>Policy-to-execution intelligence</span></div></div><div className="rt-company"><span className="environment">Assurance workspace</span><div><strong>Wexler Systems</strong><span>Security Assurance</span></div><div className="rt-avatar">DL</div></div></header>
    <div className="rt-layout">
      <aside className="rt-sidebar"><div className="standard-card"><span>Active standard</span><strong>WSEC-1 · v4.2</strong><p>SOC 2 · ISO 27001 · FedRAMP Moderate</p></div><nav>{nav.map((n)=><button key={n.id} className={view===n.id?'active':''} onClick={()=>setView(n.id)}><span>{n.number}</span>{n.label}{n.id==='impact'&&analyzed&&<b>{analysis.impact.findings.length}</b>}</button>)}</nav><div className="sidebar-footer"><div><span>Last synchronization</span><strong>Today · 14:32 IST</strong></div></div></aside>
      <section className="rt-main">
        {view==='overview'&&<Overview onStart={()=>setView('change')} baseline={analysis.baseline.score} />}
        {view==='change'&&<ChangeView before={analysis.before.text} onAnalyze={runAnalysis} />}
        {view==='impact'&&<ImpactView analyzed={analyzed} findings={analysis.impact.findings} decisions={decisions} onAnalyze={runAnalysis} onDecide={decide} />}
        {view==='execution'&&<ExecutionView entities={analysis.snapshot.entities} findings={analysis.impact.findings} analyzed={analyzed} approved={approved} />}
        {view==='evidence'&&<EvidenceView entities={analysis.snapshot.entities} findings={analysis.impact.findings} analyzed={analyzed} />}
      </section>
      <aside className="rt-rail"><Readiness score={readiness} baseline={analysis.baseline.score} after={analysis.revised.score} analyzed={analyzed} components={(analyzed?analysis.revised:analysis.baseline).components}/><ReviewQueue decided={decided} total={proposals.length}/><div className="activity"><div className="section-label">Recent activity</div>{activity.slice(0,4).map((a,i)=><p key={`${a}-${i}`}><i />{a}</p>)}</div></aside>
    </div>{toast&&<div className="rt-toast" role="status">{toast}</div>}
  </main>;
}

function PageTitle({kicker,title,description,action}:{kicker:string;title:string;description:string;action?:React.ReactNode}){return <div className="page-title"><div><span>{kicker}</span><h1>{title}</h1><p>{description}</p></div>{action}</div>}

function Overview({onStart,baseline}:{onStart:()=>void;baseline:number}){return <><PageTitle kicker="Security assurance" title="Privileged access control posture" description="Review policies, controls, delivery work, test results, exceptions, and evidence across Wexler Systems." action={<button className="rt-primary" onClick={onStart}>Open AC-2 change →</button>}/><div className="overview-hero"><div><span className="hero-kicker">Current assurance posture</span><strong>{baseline}%</strong><p>Readiness is calculated from control sufficiency, verification, evidence freshness, exception health, and unresolved proposals.</p></div><div className="hero-flow"><span>Confluence</span><i>→</i><span>Jira + Boards</span><i>→</i><span>Tests</span><i>→</i><span>Evidence</span></div></div><ConnectedSystemsExplorer/></>}

function ConnectedSystemsExplorer(){const [selected,setSelected]=useState(connectedRecords[0]);const systems=[...new Set(connectedRecords.map((r)=>r.system))];return <section className="systems-explorer"><div className="systems-toolbar"><div><span className="section-label">Connected records</span><h2>Source activity</h2></div><div className="sync-status"><i/>Last synchronized · 4 minutes ago</div></div><div className="systems-body"><aside className="systems-nav"><button className="active"><span className="system-glyph all">∞</span><div><strong>All connected work</strong><small>{connectedRecords.length} records</small></div></button>{systems.map((s)=><button key={s} onClick={()=>setSelected(connectedRecords.find((r)=>r.system===s)!)} className={selected.system===s?'selected':''}><span className={`system-glyph ${s}`}>{systemInitial(s)}</span><div><strong>{sourceLabels[s]}</strong><small>{connectedRecords.filter((r)=>r.system===s).length} record</small></div></button>)}</aside><div className="record-list"><div className="record-list-head"><strong>Recently updated</strong><span>Source · Type · Status</span></div>{connectedRecords.map((record)=><button key={record.id} className={selected.id===record.id?'selected':''} onClick={()=>setSelected(record)}><span className={`system-glyph ${record.system}`}>{systemInitial(record.system)}</span><div><small>{sourceLabels[record.system]} · {record.kind}</small><strong>{record.title}</strong><em>{record.ref}</em></div><b>{record.status}</b></button>)}</div><SourcePreview record={selected}/></div></section>}

function systemInitial(system:SourceSystem){const initials:Partial<Record<SourceSystem,string>>={confluence:'C',google_sheets:'S',jira:'J',azure_boards:'A',sharepoint:'SP',github_actions:'GH',azure_pipelines:'AZ',entra_id:'E',okta:'O',terraform_cloud:'T',servicenow:'SN',vanta:'V'};return initials[system]||sourceLabels[system].slice(0,2).toUpperCase()}

function SourcePreview({record}:{record:ConnectedRecord}){return <aside className={`source-preview preview-${record.system}`}><div className="native-bar"><span className={`system-glyph ${record.system}`}>{systemInitial(record.system)}</span><div><strong>{sourceLabels[record.system]}</strong><small>{record.owner}</small></div><button>Open source ↗</button></div><div className="native-content">{record.system==='confluence'&&<ConfluencePreview/>}{record.system==='google_sheets'&&<SheetPreview/>}{record.system==='jira'&&<TicketPreview azure={false}/>} {record.system==='azure_boards'&&<TicketPreview azure/>}{record.system==='sharepoint'&&<DecisionPreview/>}{record.system==='github_actions'&&<TestPreview azure={false}/>} {record.system==='azure_pipelines'&&<TestPreview azure/>}{record.system==='entra_id'&&<IdentityPreview okta={false}/>} {record.system==='okta'&&<IdentityPreview okta/>}{record.system==='terraform_cloud'&&<TerraformPreview/>}{record.system==='servicenow'&&<ExceptionPreview/>}{record.system==='vanta'&&<VantaPreview/>}</div><div className="trace-footer"><span>Linked requirement</span><strong>{record.kind} → AC-2</strong><b>{record.status}</b></div></aside>}

function ConfluencePreview(){return <><div className="crumbs">Wexler Security · Standards · Identity</div><h2>Privileged access authentication</h2><div className="author-row"><span>PO</span><p>Patricia Okafor<br/><small>Updated Aug 26, 2026</small></p></div><div className="doc-status">APPROVED · WSEC-1 · VERSION 4.2</div><h3>AC-2 · Requirement</h3><p>All privileged human access to production infrastructure must be authenticated with multi-factor authentication.</p><div className="info-box"><b>Control intent</b><p>Prevent unauthorized privileged access across production and Gov Cloud workloads.</p></div></>}
function SheetPreview(){return <><div className="sheet-tabs"><span>Wexler SOC2 matrix</span><b>Share</b></div><div className="formula">fx&nbsp;&nbsp; =CONTROL_MAP(B114)</div><div className="sheet-grid"><b></b><b>A</b><b>B</b><b>C</b><b>113</b><span>AC-1</span><span>Account governance</span><span className="green-cell">Effective</span><b>114</b><span>AC-2</span><span>Privileged access requires MFA</span><span className="amber-cell">Affected</span><b>115</b><span>AC-3</span><span>Access enforcement</span><span className="green-cell">Effective</span></div></>}
function TicketPreview({azure}:{azure:boolean}){return <><div className="ticket-head"><span>{azure?'Azure Boards':'Jira Software'}</span><b>{azure?'12844':'PLAT-4488'}</b></div><h2>{azure?'Enforce Conditional Access on Azure DevOps release pipelines':'FIDO2 security key rollout to Platform Identity administrators'}</h2><div className="ticket-state">● In progress</div><dl><div><dt>Assigned to</dt><dd>{azure?'S. Raghunathan':'P. Okafor'}</dd></div><div><dt>Iteration</dt><dd>{azure?'Identity\\Sprint 42':'Platform Sprint 41'}</dd></div><div><dt>Parent</dt><dd>AC-2 Privileged authentication</dd></div></dl><h3>Acceptance criteria</h3><label><input type="checkbox" checked readOnly/> Require MFA for administrative access</label><label><input type="checkbox" readOnly/> Remove weak-factor fallback</label><div className="native-warning">Acceptance criteria may be stale after AC-2 v3.</div></>}
function DecisionPreview(){return <><div className="crumbs">SharePoint · Architecture Decisions · Identity</div><span className="decision-number">ADR-024 · ACCEPTED</span><h2>Break-glass credentials remain outside the identity provider</h2><p><b>Context.</b> Regional control planes must remain accessible during a primary identity-provider outage.</p><p><b>Decision.</b> Maintain separately governed emergency credentials with monitored retrieval.</p><div className="approval-stamp">Approved by Architecture Review Board · Feb 2026</div></>}
function TestPreview({azure}:{azure:boolean}){return <><div className="run-head"><span>{azure?'Azure Pipelines':'GitHub Actions'}</span><b>✓ Run #{azure?'913':'4471'}</b></div><h2>{azure?'Service-principal credential age':'Conditional Access policy verification'}</h2><div className="run-summary"><strong>All checks passed</strong><span>Completed in 48s</span></div>{['Checkout policy repository','Evaluate deployed configuration','Assert MFA is required','Upload attestation'].map((x,i)=><div className="check-row" key={x}><span>✓</span><p>{x}</p><small>{12+i*4}s</small></div>)}<div className="native-warning">Passing test proves MFA presence—not phishing resistance.</div></>}
function IdentityPreview({okta}:{okta:boolean}){return <><div className="identity-head">{okta?'Okta Admin Console':'Microsoft Entra admin center'}</div><div className="crumbs">Protection · {okta?'Groups':'Conditional Access'} · Policies</div><h2>{okta?'Contractor production administrators':'CA-0031 · Privileged MFA policy'}</h2><span className="enabled-pill">● {okta?'ACTIVE':'ON'}</span><dl><div><dt>Applies to</dt><dd>{okta?'grp_contractor_prod':'Directory roles · Admins'}</dd></div><div><dt>Grant</dt><dd>{okta?'TOTP or FIDO2':'Require multifactor authentication'}</dd></div><div><dt>Fallback</dt><dd>{okta?'TOTP permitted':'SMS · TOTP · Push permitted'}</dd></div></dl><div className="native-warning">Configuration does not satisfy phishing-resistant-only policy.</div></>}
function TerraformPreview(){return <><div className="terraform-head">Terraform Cloud · wexler-identity-prod</div><h2>Run run-8Kq2mT</h2><div className="plan-status">✓ Applied</div><div className="plan-code"><span>Plan: 2 to add, 1 to change, 0 to destroy</span><p>~ azuread_conditional_access_policy.privileged_mfa</p><em>+ include_roles = [&quot;Global Administrator&quot;]</em><em>- allowed_factors = [&quot;sms&quot;, &quot;totp&quot;, &quot;fido2&quot;]</em></div></>}
function ExceptionPreview(){return <><div className="ticket-head"><span>ServiceNow</span><b>RITM0084412</b></div><h2>Contractor SRE authentication exception</h2><span className="exception-state">Requires reapproval</span><dl><div><dt>Requested for</dt><dd>Bangalore Support Org</dd></div><div><dt>Approver</dt><dd>Dana Lindqvist</dd></div><div><dt>Expires</dt><dd>October 10, 2026</dd></div></dl><h3>Business justification</h3><p>Hardware security keys have not been issued to contractor administrators.</p><div className="native-warning">Granted relief permits TOTP, which AC-2 v3 no longer permits.</div></>}
function VantaPreview(){return <><div className="vanta-head">Vanta · Tests</div><h2>MFA enforcement across privileged accounts</h2><div className="monitor-score"><strong>82%</strong><span>18 of 22 resources passing</span></div><div className="monitor-bar"><i style={{width:'82%'}}/></div><h3>4 resources need attention</h3>{['2 contractor admin groups','1 break-glass account','1 legacy service principal'].map((x)=><div className="monitor-row" key={x}><span>!</span>{x}</div>)}</>}

function ChangeView({before,onAnalyze}:{before:string;onAnalyze:()=>void}){return <><PageTitle kicker="Policy change · AC-2" title="Privileged access authentication" description="Review the proposed requirement against the currently approved language and its linked control scope."/><div className="change-compare"><article><div className="compare-head"><span>Approved · AC-2 v2</span><b>Confluence</b></div><h2>Current requirement</h2><p>{before}</p><div className="assertions"><span>MFA required</span><span>Weak fallback permitted</span><span>Humans + contractors</span></div></article><div className="ripple-arrow">→</div><article className="proposed"><div className="compare-head"><span>Proposed · AC-2 v3</span><b>Draft</b></div><h2>Proposed requirement</h2><p>{proposedRequirement.text}</p><div className="assertions"><span>Phishing-resistant only</span><span>No fallback</span><span>90-day review</span><span>Workload identities added</span></div></article></div><div className="analysis-callout"><div><span className="section-label">Change control</span><h3>13 linked records require review before approval.</h3><p>Source records remain unchanged until their owners approve the corresponding action.</p></div><button className="rt-primary" onClick={onAnalyze}>Refresh impact review</button></div></>}

function ImpactView({analyzed,findings,decisions,onAnalyze,onDecide}:{analyzed:boolean;findings:Finding[];decisions:Record<string,Decision>;onAnalyze:()=>void;onDecide:(id:string,d:Decision)=>void}){if(!analyzed)return <EmptyImpact onAnalyze={onAnalyze}/>; const counts=findings.reduce<Record<string,number>>((a,f)=>({...a,[f.kind]:(a[f.kind]||0)+1}),{});return <><PageTitle kicker="Impact review · AC-2 v3" title="13 linked records require attention" description="Review the policy expectation beside the current control, test, exception, or work-item state. Each response remains pending until approved by a named owner."/><div className="impact-summary">{[['New scope',counts.coverage_gap||0],['Controls',counts.control_insufficient||0],['Tests',counts.test_invalidated||0],['Exceptions',counts.exception_conflict||0],['Work items',counts.work_stale||0]].map(([l,n])=><div key={String(l)}><strong>{n}</strong><span>{l}</span></div>)}</div><div className="finding-list">{findings.map((f)=>{const p=proposalForFinding(f);const d=decisions[p.id]||'pending';return <article key={f.id} className={`finding ${d}`}><div className={`severity ${f.severity}`}>{f.severity}</div><div className="finding-body"><div><span>{f.id} · {f.kind.replaceAll('_',' ')}</span><h3>{f.summary}</h3></div><details><summary>View comparison</summary><div className="derivation"><p><b>Expected</b>{f.derivation.expected}</p><p><b>Observed</b>{f.derivation.observed}</p><small>Records: {f.derivation.comparedEntityIds.join(' · ')}</small></div></details><div className="proposal-line"><div><span>Recommended action</span><strong>{p.title}</strong></div>{d==='pending'?<div><button onClick={()=>onDecide(p.id,'rejected')}>Reject</button><button onClick={()=>onDecide(p.id,'approved')}>Approve</button></div>:<b className={d}>✓ {d} by Dana Lindqvist</b>}</div></div></article>})}</div></>}
function EmptyImpact({onAnalyze}:{onAnalyze:()=>void}){return <div className="empty-impact"><div className="empty-symbol">↯</div><span className="section-label">Impact review unavailable</span><h1>Refresh the linked records.</h1><p>Reconcile the AC-2 obligation with controls, tests, exceptions, evidence, and in-flight work.</p><button className="rt-primary" onClick={onAnalyze}>Refresh records</button></div>}

function ExecutionView({entities,findings,analyzed,approved}:{entities:Entity[];findings:Finding[];analyzed:boolean;approved:number}){const work=entities.filter((e):e is WorkItem=>e.kind==='work_item');const affected=new Set(findings.filter((f)=>f.kind==='work_stale').flatMap((f)=>f.entityIds));return <><PageTitle kicker="Connected delivery" title="Policy intent stays attached to sprint work." description="Jira and Azure Boards remain the systems of record. RippleTrace exposes when existing acceptance criteria were written for an obligation that has since moved."/><div className="execution-stats"><span>{work.length} linked work items</span><span>{analyzed?affected.size:0} stale after change</span><span>{approved} approved responses</span></div><div className="work-columns">{['backlog','in_progress','in_review','done'].map((status)=><section key={status}><div className="column-head"><strong>{status.replace('_',' ')}</strong><span>{work.filter((w)=>w.status===status).length}</span></div>{work.filter((w)=>w.status===status).map((w)=><article key={w.id} className={analyzed&&affected.has(w.id)?'affected':''}><div><span>{sourceLabels[w.sourceRef.system]}</span><b>{w.sourceRef.ref}</b></div><h3>{w.title}</h3><p>{w.ownerTeam} · {w.assignee||'Unassigned'}</p>{analyzed&&affected.has(w.id)&&<em>Acceptance criteria may be stale</em>}</article>)}</section>)}</div></>}

function EvidenceView({entities,findings,analyzed}:{entities:Entity[];findings:Finding[];analyzed:boolean}){const req=entities.find((e)=>e.id==='AC-2@2')!;const control=entities.find((e)=>e.id==='CTL-114')!;const test=entities.find((e)=>e.id==='test-entra-ca-mfa-required')!;const evidence=entities.find((e)=>e.id==='EV-01')!;return <><PageTitle kicker="Proof with provenance" title="Follow the claim from policy to evidence." description="Every relationship records its source, rationale, creator, and verification state. A passing test can still stop proving a requirement when the requirement becomes stronger."/><div className="evidence-chain">{[req,control,test,evidence].map((e,i)=><div key={e.id} className={analyzed&&['CTL-114','test-entra-ca-mfa-required','EV-01'].includes(e.id)?'affected':''}><span>{e.kind.replace('_',' ')}</span><strong>{e.id}</strong><h3>{e.title}</h3><p>{sourceLabels[e.sourceRef.system]} · {e.sourceRef.ref}</p>{i<3&&<i>→</i>}</div>)}</div>{analyzed&&<div className="proof-break"><div>!</div><section><span className="section-label">Proof gap</span><h2>The test is green. The requirement is not proven.</h2><p>{findings.find((f)=>f.kind==='test_invalidated')?.summary}</p></section></div>}<section className="surface provenance-table"><div className="surface-head"><div><span className="section-label">Trace provenance</span><h2>Every link can explain itself.</h2></div></div>{[['CTL-114 → AC-2','Control implements requirement','Google Sheets · Wexler SOC2 matrix','Verified Jun 2026'],['Test → CTL-114','Test verifies control','GitHub Actions · ca-policy.yml','Passing Aug 2026'],['EV-01 → CTL-114','Export evidences configuration','Microsoft Entra ID · CA-0031','Collected Aug 2026']].map((r)=><div className="prov-row" key={r[0]}>{r.map((x,i)=><span key={x} className={i===0?'mono':''}>{x}</span>)}</div>)}</section></>}

function Readiness({score,baseline,after,analyzed,components}:{score:number;baseline:number;after:number;analyzed:boolean;components:{label:string;score:number;weight:number}[]}){return <div className="readiness-panel"><div className="section-label">Assurance readiness</div><div className="score"><strong>{score}</strong><span>/100</span></div><div className="score-bar"><i style={{width:`${score}%`}}/></div>{analyzed&&<div className="score-delta"><span>Before {baseline}</span><b>→</b><span>After {after}</span></div>}<div className="component-list">{components.map((c)=><div key={c.label}><span>{c.label}<small>{Math.round(c.weight*100)}%</small></span><strong>{Math.round(c.score*100)}%</strong></div>)}</div></div>}
function ReviewQueue({decided,total}:{decided:number;total:number}){return <div className="journey"><div className="section-label">Review queue</div><button><i>{total-decided}</i><span>Pending decisions<small>AC-2 policy change</small></span></button><button><i>2</i><span>Owner responses due<small>Platform Identity · Cloud SRE</small></span></button><button><i>1</i><span>Exception expiring<small>ServiceNow · Oct 10</small></span></button></div>}
